### ISSUE TITLE
Cardboard settings button doesn't work

### ISSUE THREAD

**Issue by neph1** [neph1/jme-cardboard#1]
The cog-wheel indicating the settings for cardboard doesn't have any function.
My guess is it's covered by the view containing the application

**Comment by smdol** [comment]
Try adding something like this to CardboardHarness:

```
@Override
public boolean dispatchTouchEvent(MotionEvent event) 
{
    CardboardView view = getCardboardView();
    return (view != null && view.dispatchTouchEvent(event)) || super.dispatchTouchEvent(event);
}
```

**Comment by neph1** [comment]
Thanks for the tip. It seems like the events are getting hijacked somehow though because it doesn't receive any events.

**Comment by tjvdmolen** [comment]
I looked into this.

The solution @smdol provided did not work for me. 

The reason this fails is because the AndroidInputHandler calls setOnTouchListener
which in turn overrides the default onTouch call in the dispatchTouchEvent method of the View class.

The fix/workaround is to call the onTouch directly from the dispatchTouchEvent in de CardboardHarness. I will submit a pull request later today with this workaround.

**Comment by neph1** [comment]
Thanks for the fix! I'll try to incorporate this during the weekend.
